title: One-shot Voice Conversion on Different Speech Representation with Adversarial Mutual Information Learning
description: Submitted to INTERSPEECH2022
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
